"""autophonenumber

Revision ID: 404a8eda161c
Revises: 00b4ac9166fc
Create Date: 2023-06-19 16:31:10.075053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404a8eda161c'
down_revision = '00b4ac9166fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_nunmber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_nunmber')
    # ### end Alembic commands ###
